# Generated by Django 4.2.2 on 2023-06-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='followers', to='people.profile'),
        ),
    ]
