# Generated by Django 4.2.2 on 2023-06-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_profile_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(blank=True, default=63.151515),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(blank=True, default=20.155),
            preserve_default=False,
        ),
    ]
