# Generated by Django 4.2.2 on 2023-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_profile_latitude_profile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='distance',
            field=models.FloatField(blank=True, default=1, verbose_name='Расстояние'),
            preserve_default=False,
        ),
    ]
